// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class SalonAFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyzafzktvNGV2v2lkEQVkfqUb29ZinHyM',
    appId: '1:907347861596:android:03f5b8f932881602474699',
    messagingSenderId: '907347861596',
    projectId: 'gym-track-pro-salona',
    storageBucket: 'gym-track-pro-salona.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8FStBjD7o12dpELJ3wdjJzHW5SST-Jas',
    appId: '1:907347861596:ios:741d49036de2d303474699',
    messagingSenderId: '907347861596',
    projectId: 'gym-track-pro-salona',
    storageBucket: 'gym-track-pro-salona.firebasestorage.app',
    iosBundleId: 'com.example.gymTrackPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr6H3X2Nk4w3M7JOLG9i5WaKozuF0WCq8',
    appId: '1:907347861596:web:0b24ec7181033d2b474699',
    messagingSenderId: '907347861596',
    projectId: 'gym-track-pro-salona',
    authDomain: 'gym-track-pro-salona.firebaseapp.com',
    storageBucket: 'gym-track-pro-salona.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr6H3X2Nk4w3M7JOLG9i5WaKozuF0WCq8',
    appId: '1:907347861596:web:104518b2910e6e31474699',
    messagingSenderId: '907347861596',
    projectId: 'gym-track-pro-salona',
    authDomain: 'gym-track-pro-salona.firebaseapp.com',
    storageBucket: 'gym-track-pro-salona.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8FStBjD7o12dpELJ3wdjJzHW5SST-Jas',
    appId: '1:907347861596:ios:741d49036de2d303474699',
    messagingSenderId: '907347861596',
    projectId: 'gym-track-pro-salona',
    storageBucket: 'gym-track-pro-salona.firebasestorage.app',
    iosBundleId: 'com.example.gymTrackPro',
  );

}