// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwwoG8pXnDkAATgRten1Ptbjf0aylj38Q',
    appId: '1:110652860402:android:aa01371be074e3f59fed6b',
    messagingSenderId: '110652860402',
    projectId: 'gym-track-pro-a0bb0',
    storageBucket: 'gym-track-pro-a0bb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAREfYpI5LYyrmZiNqljW-QWY7Xr5bccJU',
    appId: '1:110652860402:ios:2ed3133c25f71ef99fed6b',
    messagingSenderId: '110652860402',
    projectId: 'gym-track-pro-a0bb0',
    storageBucket: 'gym-track-pro-a0bb0.firebasestorage.app',
    iosBundleId: 'com.example.gymTrackPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXBNm06LHa18SbPBlyqVT4xqOEw1dHDXg',
    appId: '1:110652860402:web:1f3e72a56d3d57ea9fed6b',
    messagingSenderId: '110652860402',
    projectId: 'gym-track-pro-a0bb0',
    authDomain: 'gym-track-pro-a0bb0.firebaseapp.com',
    storageBucket: 'gym-track-pro-a0bb0.firebasestorage.app',
    measurementId: 'G-XXS3LEW4RQ',
  );

}